name: fusion_sdk
description: A starting point for Dart libraries or applications.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  dio: ^4.0.6
  eth_sig_util: 0.0.9
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  web3dart: 2.3.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.3.2
  json_serializable: ^6.6.2
  freezed: ^2.3.5
